# PostgreSQL Version 9.1.x
#   gem install pg
#
#   Ensure the Postgres gem is defined in your Gemfile
#   gem 'pg'

# to use postgres yaml   
production:
  adapter: postgresql
  database: user-management
  username: postgres
  password: postgres
  encoding: utf8
  host: localhost
  port: 5432
  
test:
  adapter: postgresql
  database: user-management
  username: postgres
  password: postgres
  encoding: utf8
  host: localhost
  port: 5432
  
development:
  adapter: postgresql
  database: user-management
  username: postgres
  password: postgres
  encoding: utf8
  host: localhost
  port: 5432  